name: Test hoverfly

on: [push]

jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.11
      uses: actions/setup-go@v1
      with:
        go-version: 1.11
      id: go

    - name: Set up Node 6.10.3
      uses: actions/setup-node@v1
      with:
        node-version: '6.10.3'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        path: /go

    - name: Test
      run: make test
      env:
        GOFLAGS: -mod=vendor
        GOPATH: $GITHUB_WORKSPACE/go
